### ISSUE TITLE
Adicionar um timeout para o processo do comando de teste

### ISSUE THREAD

**Issue by flavioamieiro** [juanplopes/dojotimer#1]
No caso de falhas como um loop infinito o processo iniciado pelo comando de teste continua rodando indefinidamente. Seria interessante ter um limite máximo de tempo para que os testes sejam executados.

**Comment by juanplopes** [comment]
Implemented at 29de78ef1eeab78d2eb9dc0ce5c193e129558866.

**Comment by flavioamieiro** [comment]
[Quase 5 anos depois...]

Valeu @juanplopes !!

Gostei especialmente da [mudança na string](https://github.com/juanplopes/dojotimer/commit/29de78ef1eeab78d2eb9dc0ce5c193e129558866#diff-97f5b2555dfdd956cbcf67be9c3fd8c3L50) ali quando o teste falha :)
