### ISSUE TITLE
O DojoTimer não identifica os erros do Java

### ISSUE THREAD

**Issue by jonatasemidio** [juanplopes/dojotimer#4]
Faaaaala Juan!

Essa é antiga, mas resolvi postar aqui.

Após ajustar o dojotimer para rodar tanto testes em Junit(Java) quanto Spock(Groovy), percebi que mesmo os asserts retornando false o Dojotimer continuava verde com a mensagem de sucesso.

Existe uma maneira especifica para rodar Java no Dojotimer?
Caso não... Qual é a classe do Dojotimer responsável por identificar quando é um erro ou não?

**Comment by juanplopes** [comment]
Provavelmente esse é um comportamento do executável que você está usando. O DojoTimer só detecta erro se o processo terminar com um exitcode != 0. É possível que a ferramenta que você está usando para testar ignore isso.

**Comment by juanplopes** [comment]
Nothing to do in this issue.
