### ISSUE TITLE
Make font size of test results configurable

### ISSUE THREAD

**Issue by rhcarvalho** [juanplopes/dojotimer#6]
During a retrospective, one of the dojo participants noted he wished the font size in the test result screen was bigger (the popup window after running the tests).

My suggestion would be, instead of hard-coding a bigger font size, to make it configurable.

*PS: is it relevant to add issues here?*

**Comment by juanplopes** [comment]
Implemented at 3f8a950524bac8cad196ebb08592cdfaa0a16dd1. Still have to test on Linux (it was coded on Windows).

**Comment by juanplopes** [comment]
Tested on Linux Mint 17 and seems just fine.

**Comment by rhcarvalho** [comment]
Awesome, thank you!
